/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis;

import java.util.List;

public interface Lexer {
    List<TokenWrapper> analyseLexically(String line);
}
