/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis;


public class App {
  public static void main(String[] args) {
    final FileGenerator fileGenerator = new FileGenerator();
    final Lexer lexer = new Lexer();
    final Parser parser = new Parser();
    final State state = new State();
    final Token token = new Token();
    
    boolean everythingWorks = fileGenerator.method() &&
            lexer.method() && parser.method() &&
            state.method() && token.method();
    System.out.println(everythingWorks ? "Everything works" : "oh no");
  }
}
