/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis;

import java.util.Optional;

public class TokenImpl implements Token {
  
  private final TokenThing tokenThing;
  private final int line, startPos, endPos;
  private final Optional<String> value;
  
  public TokenImpl(TokenThing tokenThing, int line, int startPos, int endPos, Optional<String> value) {
    this.tokenThing = tokenThing;
    this.line = line;
    this.startPos = startPos;
    this.endPos = endPos;
    this.value = value;
  }
  
  @Override
  public int getStartPos() {
    return startPos;
  }
  
  @Override
  public int getEndPos() {
    return endPos;
  }
  
  @Override
  public int getLine() {
    return line;
  }
  
  @Override
  public TokenEnum getType() {
    return tokenThing.getType();
  }
  
  @Override
  public Optional<String> getValue() {
    return value;
  }
  
  @Override
  public String toString() {
    return getType().toString();
  }
}
