name: Gradle Package

on:
  release:
    types: [created, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish abstractsyntaxtree
        run: ./gradlew :abstractsyntaxtree:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish filegenerator
        run: ./gradlew :filegenerator:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish interpreter
        run: ./gradlew :interpreter:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish lexer
        run: ./gradlew :lexer:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish parser
        run: ./gradlew :parser:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish printer
        run: ./gradlew :printer:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish state
        run: ./gradlew :state:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish token
        run: ./gradlew :token:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}