name: Java CI + Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Google Java Format
        run: ./gradlew goJF

      - name: Static Code Analysis
        run: ./gradlew check

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           tag_name: ${{ github.ref }}
           release_name: Release ${{ github.ref }}
           body: Releasing
           draft: false
           prerelease: false

      - name: Publish abstractsyntaxtree
        run: ./gradlew :abstractsyntaxtree:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish interpreter
        run: ./gradlew :interpreter:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish lexer
        run: ./gradlew :lexer:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish parser
        run: ./gradlew :parser:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish printer
        run: ./gradlew :printer:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish state
        run: ./gradlew :state:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish token
        run: ./gradlew :token:publish
        env:
          TOKEN: ${{ secrets.TOKEN }}
