name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Google Java Format
        # You may pin to the exact commit or the version.
        # uses: axel-op/googlejavaformat-action@5045c8c244a22eb6a28eeb6050cc2baebd75c5f2
        uses: axel-op/googlejavaformat-action@v3.4.0
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_ACTOR: jisoldi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
